CREATE TABLE ADMINISTRADOR(
    CORREO_ADMINISTRADOR VARCHAR2(100),
    CONTRASEÑA_ADMINISTRADOR VARCHAR2(100)
)

--CUENTA PARA INGRESAR AL CRUD
INSERT INTO ADMINISTRADOR VALUES('Admincaja@gamers.com','123');

CREATE TABLE ESTADO_PRODUCTO(
    ID_ESTADO_PRODUCTO INT,
    NOMBRE_ESTADO_PRODUCTO VARCHAR2(150) UNIQUE NOT NULL,
    CONSTRAINT PK_ESTADO_PRODUCTO PRIMARY KEY (ID_ESTADO_PRODUCTO)
);

CREATE TABLE CATEGORIA(
    ID_CATEGORIA INT,
    NOMBRE_CATEGORIA VARCHAR2(200) UNIQUE NOT NULL,
    CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID_CATEGORIA)
);

CREATE TABLE PRODUCTO(
    ID_PRODUCTO INT,
    ID_ESTADO_PRODUCTO INT,
    ID_CATEGORIA INT,
    NOMBRE_PRODUCTO VARCHAR2(200) UNIQUE NOT NULL,
    STOCK INT NOT NULL,
    PRECIO NUMBER(15,2) NOT NULL,
    IMAGEN BLOB NOT NULL,
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO),
    CONSTRAINT FK_ESTADO_PRODUCTO FOREIGN KEY (ID_ESTADO_PRODUCTO)
    REFERENCES ESTADO_PRODUCTO (ID_ESTADO_PRODUCTO),
    CONSTRAINT FK_CATEGORIA FOREIGN KEY (ID_CATEGORIA)
    REFERENCES CATEGORIA (ID_CATEGORIA)
);

--INSERTS ESTADO PRODUCTO
INSERT INTO ESTADO_PRODUCTO VALUES(0,'INACTIVO');
INSERT INTO ESTADO_PRODUCTO VALUES(1,'ACTIVO');

--INSERTS CATEGORIA
INSERT INTO CATEGORIA VALUES(0,'MONITORES');
INSERT INTO CATEGORIA VALUES(1,'TARJETAS GRAFICAS');
INSERT INTO CATEGORIA VALUES(2,'SSDS');
INSERT INTO CATEGORIA VALUES(3,'HDDS');
INSERT INTO CATEGORIA VALUES(4,'MOTHERBOARDS');
INSERT INTO CATEGORIA VALUES(5,'MOUSES');
INSERT INTO CATEGORIA VALUES(6,'HEADSETS');
INSERT INTO CATEGORIA VALUES(7,'MOUSEPADS');
INSERT INTO CATEGORIA VALUES(8,'PROCESADORES');
INSERT INTO CATEGORIA VALUES(9,'MEMORIA RAM');

--INSERTS PRODUCTO
INSERT INTO PRODUCTO VALUES(0,1,0,'BENQ ZOWIE X113L 144Hz',100,1800000, EMPTY_BLOB());
INSERT INTO PRODUCTO VALUES(1,1,0,'BENQ ZOWIE Xl2546k 240Hz',200,2500000, EMPTY_BLOB());
INSERT INTO PRODUCTO VALUES(2,1,1,'NVIDIA RTX 3060ti',300,3000000, EMPTY_BLOB());
INSERT INTO PRODUCTO VALUES(3,0,1,'RX 6700XT',2500000,400, EMPTY_BLOB());
INSERT INTO PRODUCTO VALUES(4,0,2,'Kingston 1TB',350000,500, EMPTY_BLOB());
INSERT INTO PRODUCTO VALUES(5,0,3,'Seagate barracuda 1TB',600,120000, EMPTY_BLOB());
INSERT INTO PRODUCTO VALUES(6,1,4,'MSI B350 TOMAHAWK',350000,700, EMPTY_BLOB());
INSERT INTO PRODUCTO VALUES(7,0,5,'Logitech G203',100000,800, EMPTY_BLOB());
INSERT INTO PRODUCTO VALUES(8,1,6,'Hyperx cloud 2',250000,900, EMPTY_BLOB());
INSERT INTO PRODUCTO VALUES(9,0,8,'Ryzen 5 7600X',1200000,1000, EMPTY_BLOB());
INSERT INTO PRODUCTO VALUES(10,0,2,'KINGSTONE A400 240GB',120,120000, EMPTY_BLOB());